services:

  spring-app:
    image: hammoudiayoub/events:latest
    container_name: devops-project
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ResDB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8083"
    depends_on:
      - mysqldb
    restart: on-failure
  mysqldb:
    image: mysql:8.2.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=achat_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
